/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
/**
 * Enumeration (collection of constants).
 */
public interface ff_cb_recall_any_mask {

    public static final int FF_RCA4_TYPE_MASK_READ = -2;
    public static final int FF_RCA4_TYPE_MASK_RW = -1;

}
// End of ff_cb_recall_any_mask.java
