/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
import org.dcache.xdr.*;
import java.io.IOException;
import org.dcache.nfs.v4.xdr.nfstime4;
import org.dcache.nfs.v4.xdr.uint32_t;

public class ff_io_latency4 implements XdrAble, java.io.Serializable {
    public nfstime4 ffil_min;
    public nfstime4 ffil_max;
    public nfstime4 ffil_avg;
    public uint32_t ffil_count;

    private static final long serialVersionUID = 4758450970321975640L;

    public ff_io_latency4() {
    }

    public ff_io_latency4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ffil_min.xdrEncode(xdr);
        ffil_max.xdrEncode(xdr);
        ffil_avg.xdrEncode(xdr);
        ffil_count.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ffil_min = new nfstime4(xdr);
        ffil_max = new nfstime4(xdr);
        ffil_avg = new nfstime4(xdr);
        ffil_count = new uint32_t(xdr);
    }

}
// End of ff_io_latency4.java
