/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
import org.dcache.oncrpc4j.rpc.OncRpcException;
import org.dcache.oncrpc4j.xdr.XdrAble;
import org.dcache.oncrpc4j.xdr.XdrDecodingStream;
import org.dcache.oncrpc4j.xdr.XdrEncodingStream;
import java.io.IOException;
import org.dcache.nfs.v4.xdr.nfstime4;
import org.dcache.nfs.v4.xdr.uint64_t;

public class ff_io_latency4 implements XdrAble, java.io.Serializable {

    private static final long serialVersionUID = 4758450970321975640L;

    public uint64_t ffil_ops_requested;
    public uint64_t ffil_bytes_requested;
    public uint64_t ffil_ops_completed;
    public uint64_t ffil_bytes_completed;
    public uint64_t ffil_bytes_not_delivered;
    public nfstime4 ffil_total_busy_time;
    public nfstime4 ffil_aggregate_completion_time;

    public ff_io_latency4() {
    }

    public ff_io_latency4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ffil_ops_requested.xdrEncode(xdr);
        ffil_bytes_requested.xdrEncode(xdr);
        ffil_ops_completed.xdrEncode(xdr);
        ffil_bytes_not_delivered.xdrEncode(xdr);
        ffil_total_busy_time.xdrEncode(xdr);
        ffil_aggregate_completion_time.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ffil_ops_requested = new uint64_t(xdr);
        ffil_bytes_requested = new uint64_t(xdr);
        ffil_ops_completed = new uint64_t(xdr);
        ffil_bytes_completed = new uint64_t(xdr);
        ffil_bytes_not_delivered = new uint64_t(xdr);
        ffil_total_busy_time = new nfstime4(xdr);
        ffil_aggregate_completion_time = new nfstime4(xdr);
    }

}
// End of ff_io_latency4.java
