/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
import org.dcache.oncrpc4j.rpc.OncRpcException;
import org.dcache.oncrpc4j.xdr.XdrAble;
import org.dcache.oncrpc4j.xdr.XdrDecodingStream;
import org.dcache.oncrpc4j.xdr.XdrEncodingStream;
import java.io.IOException;

import org.dcache.nfs.v4.xdr.deviceid4;
import org.dcache.nfs.v4.xdr.io_info4;
import org.dcache.nfs.v4.xdr.length4;
import org.dcache.nfs.v4.xdr.offset4;
import org.dcache.nfs.v4.xdr.stateid4;

public class ff_iostats4 implements XdrAble, java.io.Serializable {
    public offset4 ffis_offset;
    public length4 ffis_length;
    public stateid4 ffis_stateid;
    public io_info4 ffis_read;
    public io_info4 ffis_write;
    public deviceid4 ffis_deviceid;
    public ff_layoutupdate4 ffis_layoutupdate;

    private static final long serialVersionUID = 1687051831434791943L;

    public ff_iostats4() {
    }

    public ff_iostats4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ffis_offset.xdrEncode(xdr);
        ffis_length.xdrEncode(xdr);
        ffis_stateid.xdrEncode(xdr);
        ffis_read.xdrEncode(xdr);
        ffis_write.xdrEncode(xdr);
        ffis_deviceid.xdrEncode(xdr);
        ffis_layoutupdate.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ffis_offset = new offset4(xdr);
        ffis_length = new length4(xdr);
        ffis_stateid = new stateid4(xdr);
        ffis_read = new io_info4(xdr);
        ffis_write = new io_info4(xdr);
        ffis_deviceid = new deviceid4(xdr);
        ffis_layoutupdate = new ff_layoutupdate4(xdr);
    }

}
// End of ff_iostats4.java
