/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
import org.dcache.oncrpc4j.rpc.OncRpcException;
import org.dcache.oncrpc4j.xdr.XdrAble;
import org.dcache.oncrpc4j.xdr.XdrDecodingStream;
import org.dcache.oncrpc4j.xdr.XdrEncodingStream;
import java.io.IOException;

public class ff_layoutreturn4 implements XdrAble, java.io.Serializable {
    public ff_ioerr4 [] fflr_ioerr_report;
    public ff_iostats4 [] fflr_iostats_report;

    private static final long serialVersionUID = -1266201700985015117L;

    public ff_layoutreturn4() {
    }

    public ff_layoutreturn4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = fflr_ioerr_report.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fflr_ioerr_report[$idx].xdrEncode(xdr); } }
        { int $size = fflr_iostats_report.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { fflr_iostats_report[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = xdr.xdrDecodeInt(); fflr_ioerr_report = new ff_ioerr4[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { fflr_ioerr_report[$idx] = new ff_ioerr4(xdr); } }
        { int $size = xdr.xdrDecodeInt(); fflr_iostats_report = new ff_iostats4[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { fflr_iostats_report[$idx] = new ff_iostats4(xdr); } }
    }

}
// End of ff_layoutreturn4.java
