/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
import org.dcache.oncrpc4j.rpc.OncRpcException;
import org.dcache.oncrpc4j.xdr.XdrAble;
import org.dcache.oncrpc4j.xdr.XdrDecodingStream;
import org.dcache.oncrpc4j.xdr.XdrEncodingStream;
import java.io.IOException;
import org.dcache.nfs.v4.xdr.length4;
import org.dcache.nfs.v4.xdr.uint32_t;

public class ff_layout4 implements XdrAble, java.io.Serializable {
    public length4 ffl_stripe_unit;
    public ff_mirror4 [] ffl_mirrors;
    public uint32_t ffl_flags4;
    public uint32_t ffl_stats_collect_hint;

    private static final long serialVersionUID = 9097043134498097746L;

    public ff_layout4() {
    }

    public ff_layout4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        ffl_stripe_unit.xdrEncode(xdr);
        { int $size = ffl_mirrors.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { ffl_mirrors[$idx].xdrEncode(xdr); } }
        ffl_flags4.xdrEncode(xdr);
        ffl_stats_collect_hint.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ffl_stripe_unit = new length4(xdr);
        { int $size = xdr.xdrDecodeInt(); ffl_mirrors = new ff_mirror4[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { ffl_mirrors[$idx] = new ff_mirror4(xdr); } }
        ffl_flags4 = new uint32_t(xdr);
        ffl_stats_collect_hint = new uint32_t(xdr);
    }

}
// End of ff_layout4.java
