/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
import org.dcache.oncrpc4j.rpc.OncRpcException;
import org.dcache.oncrpc4j.xdr.XdrAble;
import org.dcache.oncrpc4j.xdr.XdrDecodingStream;
import org.dcache.oncrpc4j.xdr.XdrEncodingStream;
import java.io.IOException;
import org.dcache.nfs.v4.xdr.uint32_t;

public class ff_mirrors_hint implements XdrAble, java.io.Serializable {
    public boolean ffmc_valid;
    public uint32_t ffmc_mirrors;

    private static final long serialVersionUID = 2356648982057016891L;

    public ff_mirrors_hint() {
    }

    public ff_mirrors_hint(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(ffmc_valid);
        if ( ffmc_valid == true ) {
            ffmc_mirrors.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        ffmc_valid = xdr.xdrDecodeBoolean();
        if ( ffmc_valid == true ) {
            ffmc_mirrors = new uint32_t(xdr);
        }
    }

}
// End of ff_mirrors_hint.java
