/*
 * Automatically generated by jrpcgen 1.0.7+ on 1/8/15 10:21 AM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.ff;
/**
 * A collection of constants used by the "flex_files_prot" ONC/RPC program.
 */
public interface flex_files_prot {

    public static final int FF_FLAGS_NO_LAYOUTCOMMIT = 1;
}
// End of flex_files_prot.java
