/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class ALLOCATE4args implements XdrAble {
    public stateid4 aa_stateid;
    public offset4 aa_offset;
    public length4 aa_length;

    public ALLOCATE4args() {
    }

    public ALLOCATE4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        aa_stateid.xdrEncode(xdr);
        aa_offset.xdrEncode(xdr);
        aa_length.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        aa_stateid = new stateid4(xdr);
        aa_offset = new offset4(xdr);
        aa_length = new length4(xdr);
    }

}
// End of ALLOCATE4args.java
