/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class app_data_block4 implements XdrAble {
    public offset4 adb_offset;
    public length4 adb_block_size;
    public length4 adb_block_count;
    public length4 adb_reloff_blocknum;
    public count4 adb_block_num;
    public length4 adb_reloff_pattern;
    public byte [] adb_pattern;

    public app_data_block4() {
    }

    public app_data_block4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        adb_offset.xdrEncode(xdr);
        adb_block_size.xdrEncode(xdr);
        adb_block_count.xdrEncode(xdr);
        adb_reloff_blocknum.xdrEncode(xdr);
        adb_block_num.xdrEncode(xdr);
        adb_reloff_pattern.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(adb_pattern);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        adb_offset = new offset4(xdr);
        adb_block_size = new length4(xdr);
        adb_block_count = new length4(xdr);
        adb_reloff_blocknum = new length4(xdr);
        adb_block_num = new count4(xdr);
        adb_reloff_pattern = new length4(xdr);
        adb_pattern = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of app_data_block4.java
