/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class CB_OFFLOAD4args implements XdrAble {
    public nfs_fh4 coa_fh;
    public stateid4 coa_stateid;
    public offload_info4 coa_offload_info;

    public CB_OFFLOAD4args() {
    }

    public CB_OFFLOAD4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        coa_fh.xdrEncode(xdr);
        coa_stateid.xdrEncode(xdr);
        coa_offload_info.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        coa_fh = new nfs_fh4(xdr);
        coa_stateid = new stateid4(xdr);
        coa_offload_info = new offload_info4(xdr);
    }

}
// End of CB_OFFLOAD4args.java
