/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface change_attr_type4 {

    public static final int NFS4_CHANGE_TYPE_IS_MONOTONIC_INCR = 0;
    public static final int NFS4_CHANGE_TYPE_IS_VERSION_COUNTER = 1;
    public static final int NFS4_CHANGE_TYPE_IS_VERSION_COUNTER_NOPNFS = 2;
    public static final int NFS4_CHANGE_TYPE_IS_TIME_METADATA = 3;
    public static final int NFS4_CHANGE_TYPE_IS_UNDEFINED = 4;

}
// End of change_attr_type4.java
