/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class CLONE4args implements XdrAble {
    public stateid4 cl_src_stateid;
    public stateid4 cl_dst_stateid;
    public offset4 cl_src_offset;
    public offset4 cl_dst_offset;
    public length4 cl_count;

    public CLONE4args() {
    }

    public CLONE4args(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        cl_src_stateid.xdrEncode(xdr);
        cl_dst_stateid.xdrEncode(xdr);
        cl_src_offset.xdrEncode(xdr);
        cl_dst_offset.xdrEncode(xdr);
        cl_count.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        cl_src_stateid = new stateid4(xdr);
        cl_dst_stateid = new stateid4(xdr);
        cl_src_offset = new offset4(xdr);
        cl_dst_offset = new offset4(xdr);
        cl_count = new length4(xdr);
    }

}
// End of CLONE4args.java
