/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class COPY_NOTIFY4args implements XdrAble {
    public stateid4 cna_src_stateid;
    public netloc4 cna_destination_server;

    public COPY_NOTIFY4args() {
    }

    public COPY_NOTIFY4args(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        cna_src_stateid.xdrEncode(xdr);
        cna_destination_server.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        cna_src_stateid = new stateid4(xdr);
        cna_destination_server = new netloc4(xdr);
    }

}
// End of COPY_NOTIFY4args.java
