/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class copy_requirements4 implements XdrAble {
    public boolean cr_consecutive;
    public boolean cr_synchronous;

    public copy_requirements4() {
    }

    public copy_requirements4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeBoolean(cr_consecutive);
        xdr.xdrEncodeBoolean(cr_synchronous);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        cr_consecutive = xdr.xdrDecodeBoolean();
        cr_synchronous = xdr.xdrDecodeBoolean();
    }

}
// End of copy_requirements4.java
