/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class COPY_NOTIFY4res implements XdrAble {
    public int cnr_status;
    public COPY_NOTIFY4resok resok4;

    public COPY_NOTIFY4res() {
    }

    public COPY_NOTIFY4res(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(cnr_status);
        switch (cnr_status) {
            case nfsstat.NFS_OK:
                resok4.xdrEncode(xdr);
                break;
            default:
                break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        cnr_status = xdr.xdrDecodeInt();
        switch (cnr_status) {
            case nfsstat.NFS_OK:
                resok4 = new COPY_NOTIFY4resok(xdr);
                break;
            default:
                break;
        }
    }

}
// End of COPY_NOTIFY4res.java
