/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class copy_from_auth_priv implements XdrAble {
    public secret4 cfap_shared_secret;
    public netloc4 cfap_destination;
    public utf8str_mixed cfap_username;

    public copy_from_auth_priv() {
    }

    public copy_from_auth_priv(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        cfap_shared_secret.xdrEncode(xdr);
        cfap_destination.xdrEncode(xdr);
        cfap_username.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        cfap_shared_secret = new secret4(xdr);
        cfap_destination = new netloc4(xdr);
        cfap_username = new utf8str_mixed(xdr);
    }

}
// End of copy_from_auth_priv.java
