/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class DEALLOCATE4args implements XdrAble {
    public stateid4 da_stateid;
    public offset4 da_offset;
    public length4 da_length;

    public DEALLOCATE4args() {
    }

    public DEALLOCATE4args(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        da_stateid.xdrEncode(xdr);
        da_offset.xdrEncode(xdr);
        da_length.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        da_stateid = new stateid4(xdr);
        da_offset = new offset4(xdr);
        da_length = new length4(xdr);
    }

}
// End of DEALLOCATE4args.java
