/*
 * Automatically generated by jrpcgen 1.0.7+ on 11/1/19, 1:52 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class GETXATTR4res implements XdrAble {
    public int gxr_status;
    public xattrvalue4 gxr_value;

    public GETXATTR4res() {
    }

    public GETXATTR4res(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(gxr_status);
        if (gxr_status == nfsstat.NFS_OK) {
            gxr_value.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        gxr_status = xdr.xdrDecodeInt();
        if (gxr_status == nfsstat.NFS_OK) {
            gxr_value = new xattrvalue4(xdr);
        }
    }

}
// End of GETXATTR4res.java
