/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class IO_ADVISE4args implements XdrAble {
    public stateid4 iaa_stateid;
    public offset4 iaa_offset;
    public length4 iaa_count;
    public bitmap4 iaa_hints;

    public IO_ADVISE4args() {
    }

    public IO_ADVISE4args(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        iaa_stateid.xdrEncode(xdr);
        iaa_offset.xdrEncode(xdr);
        iaa_count.xdrEncode(xdr);
        iaa_hints.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        iaa_stateid = new stateid4(xdr);
        iaa_offset = new offset4(xdr);
        iaa_count = new length4(xdr);
        iaa_hints = new bitmap4(xdr);
    }

}
// End of IO_ADVISE4args.java
