/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class IO_ADVISE4res implements XdrAble {
    public int ior_status;
    public IO_ADVISE4resok resok4;

    public IO_ADVISE4res() {
    }

    public IO_ADVISE4res(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(ior_status);
        switch (ior_status) {
            case nfsstat.NFS_OK:
                resok4.xdrEncode(xdr);
                break;
            default:
                break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        ior_status = xdr.xdrDecodeInt();
        switch (ior_status) {
            case nfsstat.NFS_OK:
                resok4 = new IO_ADVISE4resok(xdr);
                break;
            default:
                break;
        }
    }

}
// End of IO_ADVISE4res.java
