/*
 * Automatically generated by jrpcgen 1.0.7+ on 11/1/19, 1:52 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class LISTXATTRS4res implements XdrAble {
    public int lxr_status;
    public LISTXATTRS4resok lxr_value;

    public LISTXATTRS4res() {
    }

    public LISTXATTRS4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(lxr_status);
        if (lxr_status ==  nfsstat.NFS_OK) {
            lxr_value.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lxr_status = xdr.xdrDecodeInt();
        if (lxr_status ==  nfsstat.NFS_OK) {
            lxr_value = new LISTXATTRS4resok(xdr);
        }
    }

}
// End of LISTXATTRS4res.java
