/*
 * Automatically generated by jrpcgen 1.0.7+ on 11/1/19, 1:52 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class LISTXATTRS4args implements XdrAble {
    public nfs_cookie4 lxa_cookie;
    public count4 lxa_maxcount;

    public LISTXATTRS4args() {
    }

    public LISTXATTRS4args(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        lxa_cookie.xdrEncode(xdr);
        lxa_maxcount.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        lxa_cookie = new nfs_cookie4(xdr);
        lxa_maxcount = new count4(xdr);
    }

}
// End of LISTXATTRS4args.java
