/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class netloc4 implements XdrAble {
    public int nl_type;
    public utf8str_cis nl_name;
    public utf8str_cis nl_url;
    public netaddr4 nl_addr;

    public netloc4() {
    }

    public netloc4(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(nl_type);
        switch ( nl_type ) {
        case netloc_type4.NL4_NAME:
            nl_name.xdrEncode(xdr);
            break;
        case netloc_type4.NL4_URL:
            nl_url.xdrEncode(xdr);
            break;
        case netloc_type4.NL4_NETADDR:
            nl_addr.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        nl_type = xdr.xdrDecodeInt();
        switch ( nl_type ) {
        case netloc_type4.NL4_NAME:
            nl_name = new utf8str_cis(xdr);
            break;
        case netloc_type4.NL4_URL:
            nl_url = new utf8str_cis(xdr);
            break;
        case netloc_type4.NL4_NETADDR:
            nl_addr = new netaddr4(xdr);
            break;
        }
    }

}
// End of netloc4.java
