/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class OFFLOAD_STATUS4res implements XdrAble {
    public int osr_status;
    public OFFLOAD_STATUS4resok osr_resok4;

    public OFFLOAD_STATUS4res() {
    }

    public OFFLOAD_STATUS4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(osr_status);
        switch ( osr_status ) {
        case nfsstat.NFS_OK:
            osr_resok4.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        osr_status = xdr.xdrDecodeInt();
        switch ( osr_status ) {
        case nfsstat.NFS_OK:
            osr_resok4 = new OFFLOAD_STATUS4resok(xdr);
            break;
        default:
            break;
        }
    }

}
// End of OFFLOAD_STATUS4res.java
