/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class OFFLOAD_STATUS4resok implements XdrAble {
    public length4 osr_count;
    public int [] osr_complete;

    public OFFLOAD_STATUS4resok() {
    }

    public OFFLOAD_STATUS4resok(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        osr_count.xdrEncode(xdr);
        xdr.xdrEncodeIntVector(osr_complete);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        osr_count = new length4(xdr);
        osr_complete = xdr.xdrDecodeIntVector();
    }

}
// End of OFFLOAD_STATUS4resok.java
