/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class offload_info4 implements XdrAble {
    public int coa_status;
    public write_response4 coa_resok4;
    public length4 coa_bytes_copied;

    public offload_info4() {
    }

    public offload_info4(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(coa_status);
        switch (coa_status) {
            case nfsstat.NFS_OK:
                coa_resok4.xdrEncode(xdr);
                break;
            default:
                coa_bytes_copied.xdrEncode(xdr);
                break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        coa_status = xdr.xdrDecodeInt();
        switch (coa_status) {
            case nfsstat.NFS_OK:
                coa_resok4 = new write_response4(xdr);
                break;
            default:
                coa_bytes_copied = new length4(xdr);
                break;
        }
    }

}
// End of offload_info4.java
