/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class read_plus_content implements XdrAble {
    public int rpc_content;
    public data4 rpc_data;
    public data_info4 rpc_hole;

    public read_plus_content() {
    }

    public read_plus_content(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        xdr.xdrEncodeInt(rpc_content);
        switch (rpc_content) {
            case data_content4.NFS4_CONTENT_DATA:
                rpc_data.xdrEncode(xdr);
                break;
            case data_content4.NFS4_CONTENT_HOLE:
                rpc_hole.xdrEncode(xdr);
                break;
            default:
                break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        rpc_content = xdr.xdrDecodeInt();
        switch (rpc_content) {
            case data_content4.NFS4_CONTENT_DATA:
                rpc_data = new data4(xdr);
                break;
            case data_content4.NFS4_CONTENT_HOLE:
                rpc_hole = new data_info4(xdr);
                break;
            default:
                break;
        }
    }

}
// End of read_plus_content.java
