/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class READ_PLUS4args implements XdrAble {
    public stateid4 rpa_stateid;
    public offset4 rpa_offset;
    public count4 rpa_count;

    public READ_PLUS4args() {
    }

    public READ_PLUS4args(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        rpa_stateid.xdrEncode(xdr);
        rpa_offset.xdrEncode(xdr);
        rpa_count.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        rpa_stateid = new stateid4(xdr);
        rpa_offset = new offset4(xdr);
        rpa_count = new count4(xdr);
    }

}
// End of READ_PLUS4args.java
