/*
 * Automatically generated by jrpcgen 1.0.7+ on 11/1/19, 1:52 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class REMOVEXATTR4res implements XdrAble {
    public int rxr_status;
    public change_info4 rxr_info;

    public REMOVEXATTR4res() {
    }

    public REMOVEXATTR4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(rxr_status);
        if (rxr_status == nfsstat.NFS_OK) {
            rxr_info.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        rxr_status = xdr.xdrDecodeInt();
        if (rxr_status == nfsstat.NFS_OK) {
            rxr_info = new change_info4(xdr);
        }
    }

}
// End of REMOVEXATTR4res.java
