/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class SEEK4args implements XdrAble {
    public stateid4 sa_stateid;
    public offset4 sa_offset;
    public int sa_what;

    public SEEK4args() {
    }

    public SEEK4args(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        sa_stateid.xdrEncode(xdr);
        sa_offset.xdrEncode(xdr);
        xdr.xdrEncodeInt(sa_what);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        sa_stateid = new stateid4(xdr);
        sa_offset = new offset4(xdr);
        sa_what = xdr.xdrDecodeInt();
    }

}
// End of SEEK4args.java
