/*
 * Automatically generated by jrpcgen 1.0.7+ on 11/1/19, 1:52 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface setxattr_option4 {

    public static final int SETXATTR4_EITHER = 0;
    public static final int SETXATTR4_CREATE = 1;
    public static final int SETXATTR4_REPLACE = 2;

}
// End of setxattr_option4.java
