/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;

import java.io.IOException;

import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;

public class WRITE_SAME4args implements XdrAble {
    public stateid4 wsa_stateid;
    public int wsa_stable;
    public app_data_block4 wsa_adb;

    public WRITE_SAME4args() {
    }

    public WRITE_SAME4args(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
            throws OncRpcException, IOException {
        wsa_stateid.xdrEncode(xdr);
        xdr.xdrEncodeInt(wsa_stable);
        wsa_adb.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
            throws OncRpcException, IOException {
        wsa_stateid = new stateid4(xdr);
        wsa_stable = xdr.xdrDecodeInt();
        wsa_adb = new app_data_block4(xdr);
    }

}
// End of WRITE_SAME4args.java
