/*
 * Automatically generated by jrpcgen 1.0.7+ on 4/3/20, 4:01 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.nfs.v4.xdr;
import org.dcache.nfs.nfsstat;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class WRITE_SAME4res implements XdrAble {
    public int wsr_status;
    public write_response4 resok4;

    public WRITE_SAME4res() {
    }

    public WRITE_SAME4res(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(wsr_status);
        switch ( wsr_status ) {
        case nfsstat.NFS_OK:
            resok4.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        wsr_status = xdr.xdrDecodeInt();
        switch ( wsr_status ) {
        case nfsstat.NFS_OK:
            resok4 = new write_response4(xdr);
            break;
        default:
            break;
        }
    }

}
// End of WRITE_SAME4res.java
