/*
 * Automatically generated by jrpcgen 1.0.7+ on 6/19/24, 7:09 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.rquota.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface qr_status {

    public static final int Q_OK = 1;
    public static final int Q_NOQUOTA = 2;
    public static final int Q_EPERM = 3;

}
// End of qr_status.java
