/*
 * Automatically generated by jrpcgen 1.0.7+ on 6/19/24, 7:09 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.dcache.rquota.xdr;
import org.dcache.oncrpc4j.rpc.*;
import org.dcache.oncrpc4j.rpc.net.*;
import org.dcache.oncrpc4j.xdr.*;
import java.io.IOException;

public class setquota_rslt implements XdrAble {
    public int status;
    public rquota sqr_rquota;

    public setquota_rslt() {
    }

    public setquota_rslt(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(status);
        switch ( status ) {
        case qr_status.Q_OK:
            sqr_rquota.xdrEncode(xdr);
            break;
        case qr_status.Q_NOQUOTA:
            break;
        case qr_status.Q_EPERM:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        status = xdr.xdrDecodeInt();
        switch ( status ) {
        case qr_status.Q_OK:
            sqr_rquota = new rquota(xdr);
            break;
        case qr_status.Q_NOQUOTA:
            break;
        case qr_status.Q_EPERM:
            break;
        }
    }

}
// End of setquota_rslt.java
